from .alquiler import AlquilerFormulario
from .alquiler_servicio import AlquilerServicioFormulario
from .calificacion_alquiler import CalificacionAlquilerFormulario
from .confirmar_alquiler import ConfirmarAlquilerFormulario