from .alquiler import AlquilerFormulario
from .alquiler_servicio import AlquilerServicioFormulario
from .calificacion_alquiler import CalificacionAlquilerFormulario
from .eventualidad import EventualidadFormulario
from .foto_alquiler import FotoAlquilerFormulario
from .promocion import PromocionFormulario
from .confirmar_alquiler import ConfirmarAlquilerFormulario